export const PERP_MARKETS = [
    {
        "name": "BTC-PERP",
        "publicKey": "DtEcjPLyD4YtTBB4q8xwFZ9q49W89xZCZtJyrGebi5t8",
        "baseSymbol": "BTC",
        "baseDecimals": 6,
        "quoteDecimals": 6,
        "marketIndex": 1,
        "bidsKey": "Bc8XaK5UTuDSCBtiESSUxBSb9t6xczhbAJnesPamMRir",
        "asksKey": "BkWRiarqxP5Gwx7115LQPbjRmr3NjuSRXWBnduXXLGWR",
        "eventsKey": "7t5Me8RieYKsFpfLEV8jnpqcqswNpyWD95ZqgUXuLV8Z",
        "contractSize": 0.0001,
        "perpMarketId": 1,
        "leverage": 20
    },
    {
        "name": "ETH-PERP",
        "publicKey": "DVXWg6mfwFvHQbGyaHke4h3LE9pSkgbooDSDgA4JBC8d",
        "baseSymbol": "ETH",
        "baseDecimals": 6,
        "quoteDecimals": 6,
        "marketIndex": 2,
        "bidsKey": "DQv2sWhaHYbKrobHH6jAdkAXw13mnDdM9hVfRQtrUcMe",
        "asksKey": "8NhLMV6huneGAqijuUgUFSshbAfXxdNj6ZMHSLb9aW8K",
        "eventsKey": "9vDfKNPJkCvQv9bzR4JNTGciQC2RVHPVNMMHiVDgT1mw",
        "contractSize": 0.001,
        "perpMarketId": 2,
        "leverage": 10
    },
    {
        "name": "SOL-PERP",
        "publicKey": "2TgaaVoHgnSeEtXvWTx13zQeTf4hYWAMEiMQdcG6EwHi",
        "baseSymbol": "SOL",
        "baseDecimals": 9,
        "quoteDecimals": 6,
        "marketIndex": 3,
        "bidsKey": "Fu8q5EiFunGwSRrjFKjRUoMABj5yCoMEPccMbUiAT6PD",
        "asksKey": "9qUxMSWBGAeNmXusQHuLfgSuYJqADyYoNLwZ63JJSi6V",
        "eventsKey": "31cKs646dt1YkA3zPyxZ7rUAkxTBz279w4XEobFXcAKP",
        "contractSize": 0.01,
        "perpMarketId": 3,
        "leverage": 10
    },
    {
        "name": "AVAX-PERP",
        "publicKey": "EAC7jtzsoQwCbXj1M3DapWrNLnc3MBwXAarvWDPr2ZV9",
        "baseSymbol": "AVAX",
        "baseDecimals": 8,
        "quoteDecimals": 6,
        "marketIndex": 12,
        "bidsKey": "BD1vpQjLXx7Rmd5n1SFNTLcwujPYTnFpoaArvPd9ixB9",
        "asksKey": "8Q11iGHXFTr267J4bgbeEeWPYPSANVcs6NQWHQK4UrNs",
        "eventsKey": "5Grgo9kLu692SUcJ6S7jtbi1WkdwiyRWgThAfN1PcvbL",
        "contractSize": 0.01,
        "perpMarketId": 12,
        "leverage": 10
    },
    {
        "name": "LUNA-PERP",
        "publicKey": "BCJrpvsB2BJtqiDgKVC4N6gyX1y24Jz96C6wMraYmXss",
        "baseSymbol": "LUNA",
        "baseDecimals": 6,
        "quoteDecimals": 6,
        "marketIndex": 13,
        "bidsKey": "AiBurBkETJHHujZxNHm6UPvBQ1LLLkNkckPoZLeuLnS1",
        "asksKey": "7Vcbxj2M8fqaNGfRDsau47uXumfCBhCTA97D6PNDPWfe",
        "eventsKey": "HDJ43o9Dxxu6yWRWPEce44gtCHauRGLXJwwtvD7GwEBx",
        "contractSize": 0.01,
        "perpMarketId": 13,
        "leverage": 10
    },
]